export enum Genre {
	Ambient = "Ambient",
	Breakcore = "Breakcore",
	CloudRap = "Cloud Rap",
	DrumAndBass = "Drum and Bass",
	Dubstep = "Dubstep",
	Electronic = "Electronic",
	EmoRap = "Emo Rap",
	Experimental = "Experimental",
	FutureBass = "Future Bass",
	FutureGarage = "Future Garage",
	HipHop = "Hip-hop",
	Indie = "Indie",
	IndieRock = "Indie Rock",
	Jungle = "Jungle",
	LoFi = "Lo-Fi",
	MemphisRap = "Memphis Rap",
	Mix = "Mix",
	Phonk = "Phonk",
	Pop = "Pop",
	Rock = "Rock",
	Synthwave = "Synthwave",
	Techno = "Techno",
	Trap = "Trap",
	TripHop = "Trip-hop",
	Vaporwave = "Vaporwave",
}
